// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Sales.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Sales.Data
{
    public partial interface ISalesDbContextProcedures
    {
        Task<List<items_countResult>> items_countAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<total_priceResult>> total_priceAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
