// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sales.Models
{
    public partial class items_countResult
    {
        public int? items_Count { get; set; }
    }
}
